### ISSUE TITLE
Music in IWD broken after installation

### ISSUE THREAD

**Issue by TMaluszynski** [The-Gate-Project/IWD1_EET#16]
Music in Icewind Dale in EET has a weird chirping sound that I've been unable to remove thus far.

It's a high pitched sound as if a speaker was broken, no other sounds are affected. Icewind Dale Enhanced Edition does not suffer from this.

Installed mods (in order):
-EET
-IWD1
-IWD2
-Cowled Menace
-NWNforBG2
-EEeX
-Wild Mage
-subrace
-d2-weapon
-bp-bgt-worldmap
-EET Tweaks
-IWD end
-EET end

**Comment by 11jo** [comment]
Hello,

Thanks for the bug report, I don't know how to fix this yet but the issue is investigated.

**Comment by 11jo** [comment]
Many Thanks @GraionDilach !

@TMaluszynski, if you'd like to confirm that the fix has solved your problem, please let us know.

**Comment by TMaluszynski** [comment]
@11jo, @GraionDilach  great work guys, issue is fixed as far as I could tell from a short 15-minute checkup on various locations.
