### ISSUE TITLE
SHELFPS1.baf and SHSHDSD1.baf syntax error issues [FIXABLE BY YOURSELF]

### ISSUE THREAD

**Issue by cygarniczka** [The-Gate-Project/IWD1_EET#5]
Both of above mentioned files have syntax errors easily fixed by changing 

`    See(EigthNearestMyGroupOfType)`

to

` See(EighthNearestMyGroupOfType)`

SHELFPS1.baf and SHSHDSD1.baf contain both two instances of such syntax error.

**Comment by 11jo** [comment]
It took me a while...

Thanks Zelazko !
